/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

// Imports utility for versioning
const {
  versionSelector,
  versionCrumb
} = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");

// Import the versions.json file, generates a version selector dynamically
const apidocsVersions = require("./docs/api-docs/versions.json");

module.exports = {
  apisidebar: [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(apidocsVersions), // Version selector using the imported versions.json
      className: "version-button", // Class for styling
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`), // Crumb to display the current version
    },
    {
      type: 'autogenerated', // Pull in API docs from api-docs dir
      dirName: 'api-docs', // Path to the API docs folder
    },
  ],
};
