#!/bin/bash

# Step 1. give script access to terminal (tty)
# for interactive commit message generation.
exec < /dev/tty 

# Step 2. run commitizen w/out local installation,
# fallback to doing nothing if fails.
pnpm cz --hook || true
